export const fakeUsers = [
  { name: "Ramesh", xp: 140, isCurrentUser: false },
  { name: "Sita", xp: 120, isCurrentUser: false },
  { name: "Lakshmi", xp: 110, isCurrentUser: false },
  { name: "Gangi", xp: 105, isCurrentUser: false },
  { name: "Pooja", xp: 100, isCurrentUser: false },
  { name: "Gopal", xp: 95, isCurrentUser: false },
  { name: "Shanti", xp: 88, isCurrentUser: false },
  { name: "Kiran", xp: 82, isCurrentUser: false },
  { name: "Bablu", xp: 74, isCurrentUser: false },
  { name: "Radha", xp: 70, isCurrentUser: false },
  { name: "Munna", xp: 66, isCurrentUser: false },
  { name: "Lata", xp: 60, isCurrentUser: false },
  { name: "Sundar", xp: 52, isCurrentUser: false },
  { name: "Kamla", xp: 48, isCurrentUser: false },
  { name: "Raju", xp: 44, isCurrentUser: false },
  { name: "Meena", xp: 40, isCurrentUser: false },
  { name: "Bittu", xp: 36, isCurrentUser: false },
  { name: "Sarita", xp: 30, isCurrentUser: false },
  { name: "Chotu", xp: 24, isCurrentUser: false },
  { name: "Rekha", xp: 20, isCurrentUser: false },
] as const;
